### ISSUE TITLE
Should we join forces?

### ISSUE THREAD

**Issue by raelgc** [plaidchat/plaidchat#142]
Hi plaidchat team, how are you?

Some months ago, I started a similar app, [ScudCloud](https://github.com/raelgc/scudcloud) with the same goal: a open source client for Slack on Linux, as on that time, Slack has no offer for a Linux client.

Now, they offer a Linux client, while not open source.

I can see in the opened issues here that we face a lot of similar problems, and we're using similar strategies to offer a Linux client (while ScudCloud uses python + qtwebkit) to render the web version.

And I'm always a guy asking why a lot of similar open source projects do not join forces, I'm here to say: maybe we can join forces and produce just one open source client.

**Comment by twolfson** [comment]
From my perspective, things have started to dry up around this project and I have lost motivation to continue developing on this since there's an official client with much more frequent releases.

While the official client isn't libre (open as in freedom) per-se, its underlying source code is definitely viewable/editable (open as in accessible). I left some notes on how to view its contents here:

https://github.com/plaidchat/plaidchat/issues/128#issuecomment-141723281

If you dig around a bit, you will notice that most of the code is done via their website (i.e. not the client). As a result, integrations become brittle -- unless we rely on their API which won't deliver nearly as much info as their own client. Can you explain why you are interested in building something to hit a moving target?

**Comment by raelgc** [comment]
@twolfson thank you for your answers.

And thank you for pointing that issue. It clarified a lot of things.

**Comment by twolfson** [comment]
It sounds like this thread is ready to be closed so closing it for now.
