### ISSUE TITLE
Empty menu entry

### ISSUE THREAD

**Issue by garagatyi** [plaidchat/plaidchat#31]
Ubuntu 12.04, slack-for-linux 0.12.0
https://dl.dropboxusercontent.com/1/view/uhc9yk1xcpync12/Apps/Shutter/Selection_048.png

**Comment by twolfson** [comment]
The file seems to be protected. You can upload the screenshot directly on GitHub by dragging and dropping into the comment box.

**Comment by garagatyi** [comment]
![selection_048](https://cloud.githubusercontent.com/assets/1851863/7062410/a6691ffc-dea5-11e4-8966-cb1e9dced687.png)

**Comment by twolfson** [comment]
This seems to be a bug in `nw.js` with Gnome and Unity so we seem to be dependant on that being fixed =/

https://github.com/nwjs/nw.js/issues/2990

Also relevant issues that might fix the problem:

https://github.com/nwjs/nw.js/issues/261

https://github.com/nwjs/nw.js/pull/2327

**Comment by garagatyi** [comment]
ok
BTW is it possible to change default behaviour of the icon on left mouse button click from `open menu` to `activate the window`

**Comment by twolfson** [comment]
Currently left click is bound to toggling visibility (i.e. minimized/visible). Either 1 or 2 clicks will trigger the window being active. This seems to be a common paradigm in notification bars.

https://github.com/wlaurance/slack-for-linux/blob/v1.2.1/app/js/index.js#L93

I am going to guess the "Open menu" interaction is being caused by the same bug as the empty menu item =/

**Comment by damiandennis** [comment]
same issue here is Ubuntu 14.04

**Comment by Mte90** [comment]
confirmed on kde 5

**Comment by twolfson** [comment]
@Mte90 I was unable to find a relevant KDE 5 issue on `nw.js`. Do you think you could file an issue on `nw.js`?

https://github.com/nwjs/nw.js/issues
