### ISSUE TITLE
Framework discussion

### ISSUE THREAD

**Issue by wlaurance** [plaidchat/plaidchat#38]
In previous PR's it's been noted the code is growing and getting messy.

What are the suggestions?

I suppose we can do almost anything from the array of frontend JS technologies.

@twolfson

**Comment by twolfson** [comment]
Yea, we need some way to maintain application state. Especially now that we have multiple teams which have their own set of notifications and windows.

The best choice would be to pick up a framework (e.g. Backbone, Angular, Ember, React). My vote would be for React since it handles state changes very well.

**Comment by wlaurance** [comment]
OK cool. I've been looking for an excuse to learn React.

**Comment by twolfson** [comment]
Sweet, that was easy =)

To make sure we are on the same page, are you going to perform the React refactor or am I?

**Comment by wlaurance** [comment]
You are welcome to start!

**Comment by twolfson** [comment]
I am going to hold off on this until my 3 new PRs have landed/been settled. I don't want too many things up in the air =/

**Comment by twolfson** [comment]
I forgot to post this earlier but I started jamming on React earlier this week. It's coming along with a few bumps (due to our app being in nw.js and us not knowing all our application state upfront).

At the moment, I have a proof of concept that is loading multiple teams without any jittering refresh for the first team. I don't have an ETA as I am doing this leisurely. However, I would expect it to be done within the next 2 weeks.

**Comment by twolfson** [comment]
I should also note that I am hesitant about React a little due to:

- Fighting it for things like application state
- It might be a larger barrier to entry for contributors

But on the other hand:

- We don't have to worry about managing adding/removing/cleaning up team sidebar
- We might have wound up doing something bespoke which would have an even bigger barrier to entry

All in all, I think it's a decent set of tradeoffs and it gives us experience with React which is a plus.

**Comment by wlaurance** [comment]
Can application state be handled by another module?

I think we can combat the barrier to entry by providing a short guide with how to add a feature?

**Comment by twolfson** [comment]
Not really, the main problem is iframes which is on the HTML/DOM side which is where React mostly works =/

Yea, we can definitely provide a short guide but reading too is a barrier to entry ;)
