### ISSUE TITLE
Add keyboard shortcuts for switching between teams

### ISSUE THREAD

**Issue by twolfson** [plaidchat/plaidchat#40]
In the desktop clients, we can switch between teams via keyboard shortcuts. We should add similar functionality.

![Screenshot](http://a4.mzstatic.com/us/r30/Purple3/v4/88/86/9b/88869b89-cde5-5a50-26cc-3fcd181e8806/screen800x500.jpeg)

**Comment by captn3m0** [comment]
While the Mac app uses `Cmd+{num}` as the team shortcut, considering this is Linux, there is a considerable chance that Super+1 is already taken by the Window Manager.

For eg, my i3 setup uses Super+num to switch between workplaces. I think this is the default in Elementary as well. I would like to go with Alt+num, which is used by Chrome (Firefox?) in Linux, but again since this would be taken up by many, customization makes most sense.

**Comment by twolfson** [comment]
The typical parallel for Windows/Linux to OSX is ctrl <-> cmd. I was planning on using Ctrl+1, Ctrl+2. Would that work for you as well?

Also, can a Windows user verify that the Windows client uses Ctrl? /cc @mathieumg

**Comment by captn3m0** [comment]
Yeah, Ctrl would work for me as well.

**Comment by mathieumg** [comment]
@twolfson I only have Linux at work :sunglasses: 

I just asked a friend, he confirms it's ctrl + # on Windows.

**Comment by twolfson** [comment]
Cool, we will probably stick with Ctrl then for consistency =)

**Comment by dozoisch** [comment]
![image](https://cloud.githubusercontent.com/assets/4422516/8318301/4e1a3dce-19b8-11e5-90e5-458f4a8aac01.png)
This is what it looks likes on windows if you want to show the same in the ui! (the little ^<number>)

**Comment by twolfson** [comment]
Yep, that's quite universal for indicating Ctrl =)
